### Create a new user
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "userId": "NewUserTest",
    "firstName": "Piseth",
    "lastName": "Cee",
    "email": "PCee92@gmail.com",
    "password": "tempPass"
}

### Create a new job
POST http://localhost:5000/api/jobs HTTP/1.1
Content-Type: application/json

{
    "title": "Software Engineer",
    "description": "Develop and maintain web applications using the MERN stack.",
    "company": "CapTech",
    "location": "New York, NY"
}

### Create a new contact
POST http://localhost:5000/api/contacts HTTP/1.1
Content-Type: application/json

{
    "name": "Joe Smith",
    "email": "Joe.smith@techcorp.com",
    "phoneNumber": "+123450009",
    "company": "CapTech",
    "jobTitle": "IT Manager",
    "notes": "Met at the Atlassian 2023 conference.",
    "user": "6544657d3b3f9f8cc519430c",
    "relatedJobs": "654466d77e3869761063369c"
}

### Create a new skill
POST http://localhost:5000/api/skills HTTP/1.1
Content-Type: application/json

{
    "name": "Python",
    "description": "A versatile programming language that has many uses",
    "category": "Programming Language"
}


### Add a skill to a user
POST http://localhost:5000/api/user-skills HTTP/1.1
Content-Type: application/json

{
    "userId": "65359b1fad885d08ea13bc97",
    "skillId": "653b35a1f0268571ab6c651c",
    "proficiency": "Intermediate"
}

### Add a skill requirement to a job
POST http://localhost:5000/api/job-skills HTTP/1.1
Content-Type: application/json

{
    "jobId": "654466d77e3869761063369c",
    "skillId": "653b35a1f0268571ab6c651c",
    "importance": "Essential"
}

### Add a job application for a user
POST http://localhost:5000/api/user-applications HTTP/1.1
Content-Type: application/json

{
    "userId": "65359b1fad885d08ea13bc97",
    "jobId": "653b3046d21aebc7f3f259f0",
    "dateApplied": "2023-10-20",
    "status": "Pending",
    "notes": "Applied through company website. Waiting for HR response."
}

### Update a user
PUT http://localhost:5000/api/users/6544572c5c5c75a8597df342 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Piseth",
    "lastName": "Chewy",
    "email": "UpdatedEmail@example.com",
    "password": "UpdatedPassword"
}

### Delete a user
DELETE http://localhost:5000/api/users/6544572c5c5c75a8597df342 HTTP/1.1

### Update a user skill
PUT http://localhost:5000/api/user-skills/653d8a80c2715a9e65b38887 HTTP/1.1
Content-Type: application/json

{
    "userId": "6544657d3b3f9f8cc519430c",
    "skillId": "6544650a3b3f9f8cc519430a",
    "proficiency": "Intermediate"
}

### Delete a user skill
DELETE http://localhost:5000/api/user-skills/653d8a80c2715a9e65b38887 HTTP/1.1


### Update a job skill
PUT http://localhost:5000/api/job-skills/654467077e3869761063369e HTTP/1.1
Content-Type: application/json

{
    "jobId": "654466d77e3869761063369c",
    "skillId": "653b35a1f0268571ab6c651c",
    "importance": "High"
}

### Delete a job skill
DELETE http://localhost:5000/api/job-skills/654467077e3869761063369e HTTP/1.1

### Update a job
PUT http://localhost:5000/api/jobs/653d8a74c2715a9e65b38881 HTTP/1.1
Content-Type: application/json

{
    "title": "UpdatedJobTitle",
    "company": "UpdatedCompany",
    "description": "Updated job description here.",
    "status": "Applied",
    "userId": "UserID_Associated_with_this_Job"
}

### Delete a job
DELETE http://localhost:5000/api/jobs/653d8a74c2715a9e65b38881 HTTP/1.1

### Update a contact
PUT http://localhost:5000/api/contacts/6544727fd40900a7312dffdd HTTP/1.1
Content-Type: application/json

{
    "name": "UpdatedName",
    "email": "updated.email@example.com",
    "phoneNumber": "123-456-7890",
    "company": "UpdatedCompany",
    "jobTitle": "UpdatedJobTitle",
    "notes": "Updated notes about this contact",
    "user": "65359b1fad885d08ea13bc97",
    "relatedJobs": "653b3046d21aebc7f3f259f0"
}

### Delete a contact
DELETE http://localhost:5000/api/contacts/6544727fd40900a7312dffdd HTTP/1.1

### Update a skill
PUT http://localhost:5000/api/skills/6544650a3b3f9f8cc519430a HTTP/1.1
Content-Type: application/json

{
    "name": "Python3",
    "description": "A versatile programming language that has many uses"
}

### Delete a skill
DELETE http://localhost:5000/api/skills/654473ef8ecd297c5f38d3d7 HTTP/1.1

### Update a user application
PUT http://localhost:5000/api/user-applications/6544760bc1e136734bff52c0 HTTP/1.1
Content-Type: application/json

{
    "userId": "65359b1fad885d08ea13bc97",
    "jobId": "653b3046d21aebc7f3f259f0",
    "status": "Rejected"
}

### Delete a user application
DELETE http://localhost:5000/api/user-applications/6544760bc1e136734bff52c0 HTTP/1.1

### Create a new user
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Piseth",
    "lastName": "Cee",
    "email": "PC92@gmail.com",
    "password": "tempPass"
}

### Update a user
PUT http://localhost:5000/api/users/65492bb551438bfc653322bf HTTP/1.1
Content-Type: application/json

{
    "firstName": "PisethTest",
    "email": "PC90@gmail.com"
}

### Delete a user
DELETE http://localhost:5000/api/users/65492bb551438bfc653322bf HTTP/1.1


### User login
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "PCee92@gmail.com",
    "password": "tempPass"
}
